version: "3.9"
services:
  go-server-1:
    build:
      context: ./../go-server-1
      dockerfile: ./../go-server-1/api-server.dockerfile
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1
  go-server-2:
    build:
      context: ./../go-server-2
      dockerfile: ./../go-server-2/api-server.dockerfile
    ports:
      - "8002:8002"
    deploy:
      mode: replicated
      replicas: 1
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./temp/:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./temp/:/var/lib/rabbitmq/
